### ISSUE TITLE
Does vivecraft require optifine?

### ISSUE THREAD

**Issue by intergrav** [jrbudda/Vivecraft_118#12]
Im using multimc, and im using mods other than optifine like sodium, iris, and a ton of performance mods. I would like to use them with non-vr, but it auto installs optifine. Is optifine required for vivecraft to work, or is there a way to remove optifine from the installation? Also, does it work with fabric?

**Comment by Zaprit** [comment]
As far as i can tell, no:
A. Optifine is requires (probably because it's got a decent api to do these vr things)
B. No it doesn't work with fabric
From the FAQ:

> # Does Vivecraft work with Fabric?
> No. Vivecraft is based on Optifine and cannot be compatible with Fabric without a major re-write. Additionally, A fabric-compatible Vivecraft would still have conflicts with other mods that modify rendering (like Sodium or Canvas). We have no current plans to pursue Fabric, but may revisit this in the future when the Fabric ecosystem is more mature.

**Comment by CalebDaMaker** [comment]
hes probably talking about forge ports like Rubidium(sodium) and Oculus(iris+starlight)

**Comment by CalebDaMaker** [comment]
If you do want a fabric version try https://github.com/Sorenon/MCXR or https://sidequestvr.com/app/7150/questcraft
QuestCraft supports standalone, but you have to watch a tutorial and a lot of times has annoying problems. It only supports Quest (I think)
