### ISSUE TITLE
controllers not tracking

### ISSUE THREAD

**Issue by Gamerjimjam** [jrbudda/Vivecraft_118#23]
this is not a steam vr issue, when i go in steam vr home, my controllers work fine, but when in vivecraft, controllers are unable to move

**Comment by TheJokingTeen** [comment]
I heard from jrbudda that you need to make sure Steam (not only SteamVR) is running. Steam apparently handles communication between the SteamVR tracking and the game.

**Comment by Gamerjimjam** [comment]
steam and steam vr were always running

**Comment by TheJokingTeen** [comment]
> steam and steam vr were always running

Hm, strange

**Comment by mmaniac01** [comment]
Hi Gamerjimjam,

What controllers are you using?

**Comment by Gamerjimjam** [comment]
i forgot about this issue, it somehow fixed iself eventually
