### ISSUE TITLE
Diamond blocks are not dropping.

### ISSUE THREAD

**Issue by Syntheticsun** [jrbudda/Vivecraft_118#24]
The diamond blocks are only colored on one side and do not drop diamonds when mined with an Iron Pick.  I have tried building two worlds and after hours of game play in each world I am not able to mine diamonds.  
Please help

**Comment by Syntheticsun** [comment]
![2022-02-23_16 45 12](https://user-images.githubusercontent.com/100400968/155741411-0d90d4f1-c3b4-4044-8382-da4848400be6.png)
![2022-02-23_16 45 12](https://user-images.githubusercontent.com/100400968/155741611-b969bf73-b405-433b-b9bc-46bb03edd3b4.png)

**Comment by Syntheticsun** [comment]
![2022-02-25_08 40 06](https://user-images.githubusercontent.com/100400968/155744061-7a0506af-a0fd-4e4c-b998-3d353e758ca8.png)

**Comment by Syntheticsun** [comment]
[2022-02-24-6.log.gz](https://github.com/jrbudda/Vivecraft_118/files/8142402/2022-02-24-6.log.gz)

**Comment by TheCleric00** [comment]
That's not diamond, it's glow lichen. It appears on the side of underground stones and emits a small amount of light.

**Comment by Syntheticsun** [comment]
Ok, thank you.  I’ve never seen them before, I’m a newb in the Minecraft world.  Thank you.
