### ISSUE TITLE
Italian language listed on Transifex, but unable to apply

### ISSUE THREAD

**Issue by GabJustGab** [jrbudda/Vivecraft_118#48]
I have no idea if this is the right place where to ask in the first place, but when trying to apply for the Italian translation of the project on Transifex it doesn't appear on the dropdown menu.
I know for sure that it is a requested language as I checked the list, but for whatever reason I can't apply.
Any reason for that or is it just a bug?

Thank you in advance

**Comment by Techjar** [comment]
May just be a glitch in the UI. I accepted your join request so you should have access now.
