### ISSUE TITLE
Iris Shaders support (and maybe fabric)

### ISSUE THREAD

**Issue by Muda42** [jrbudda/Vivecraft_118#9]
[Iris Shaders](https://irisshaders.net/) is an open source alternative to OptiFine based on Fabric. The fact that it's open source, allows it to be updated very rapidly. I think it wouldn't be such a bad idea to create a Vivecraft flavour based on IrisShaders and perhaps even full Fabric integration

**Comment by mmaniac01** [comment]
Hi Muda42,

Vivecraft required OptiFine for more than just shader support. It will not work with Fabric. However, [MCXR](https://github.com/Sorenon/MCXR) might do what you're looking for.
